### ISSUE TITLE
IndexError: index 4 is out of bounds for axis 2 with size 4

### ISSUE THREAD

**Issue by spoon0525** [matciotola/Z-PNN#5]
why it shows this error: 
Traceback (most recent call last):
  File "C:\Users\phon0\Desktop\Z-PNN-master\main.py", line 312, in <module>
    main_zpnn(arguments)
  File "C:\Users\phon0\Desktop\Z-PNN-master\main.py", line 117, in main_zpnn
    LSpec = losses.SpectralLossNocorr(generate_mtf_variables(s.ratio, sensor, I_PAN, I_MS),
  File "C:\Users\phon0\Desktop\Z-PNN-master\spectral_tools.py", line 186, in generate_mtf_variables
    temp = xcorr(img_ms[:, :, b], P[i::ratio, j::ratio], 2)
IndexError: index 4 is out of bounds for axis 2 with size 4
its seems to have something to do with the color channel, when i use ms.tif with rgb channel, it will shows:
Traceback (most recent call last):
  File "C:\Users\phon0\Desktop\Z-PNN-master\main.py", line 312, in <module>
    main_zpnn(arguments)
  File "C:\Users\phon0\Desktop\Z-PNN-master\main.py", line 117, in main_zpnn
    LSpec = losses.SpectralLossNocorr(generate_mtf_variables(s.ratio, sensor, I_PAN, I_MS),
  File "C:\Users\phon0\Desktop\Z-PNN-master\spectral_tools.py", line 186, in generate_mtf_variables
    temp = xcorr(img_ms[:, :, b], P[i::ratio, j::ratio], 2)
IndexError: index 3 is out of bounds for axis 2 with size 3
is there any possible step that i missed? cause few month ago I use this file and it work successfully

**Comment by spoon0525** [comment]
it seems related to sensor, when I use GeoEye1, it can work successfully, but when I use WorldView-3  or WorldView-2, it will show the error above

**Comment by matciotola** [comment]
I will check it next week (I am out of the office until the 16th). Thank you for highlighting the issue!
Can you give me more information about the image sizes?

**Comment by matciotola** [comment]
@spoon0525 I have checked the entire code and run several experiments. I didn't find unexpected behaviours, the code works fine.
Please, check your images and be sure to select the correct sensor:

python main.py -i /path/to/image -m Z-PNN -s GE1
for GeoEye-1 satellite.
If you still have problems with the code feel free to open new issues, reopen this or send me an e-mail, I will be happy to help you!
MC
